spring:
  datasource:
        name: oauth2
        username: root
        password:
        url: jdbc:mysql://localhost:3306/oauth2

  http:
        encoding:
          force: true
          charset: UTF-8
          enabled: true

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
